### PR TITLE
Changed global geotag map to use solr data

### PR DESCRIPTION
**Pull request by andrebola**
issue #652

The idea with this is to test global geomap to check if works faster with solr.

### CODE REVIEW

**Comment by ffont** [comment]
I just tested that in freesound test and the obtained results do not seem to be the same using solr than before. See the attached images below. First one corresponds to geotags map before using solr, second one geotags map when using solr. Something is clearly wrong. This should be investigated.

before

after

**Comment by andrebola** [comment]
@ffont is it possible solr in test doesn't have all the sounds?

**Comment by ffont** [comment]
It does not have all the sounds but this should not be a problem
The comparison is with pg-based geotags and solr-based geotags in test (I see the same in local).
Maybe the problem is just that solr index is not updated (that would be a first thing to try locally).
However I think that the problem is that solr is returning way less results that pg. I guess solr can't return all results at once, so it is possible that we won't really be able to implement this geotags thing using solr. Same problem we had with the combined search in the API.

**Comment by andrebola** [comment]
In solr the information of lat and long was in other order that is why they were in the wrong position in the map. 
Let's try on test if solr is returning all the items, in my local works fine with around 4k items.

**Comment by bdejong** [comment]
Te biggest problem with this approach (getting the lat/lon from Solr) is
that IIRC we don't invalidate and resubmit sounds to Solr at all. I.e.the
Solr index is always out of date...

I also don't really understand why Solr would be quicker at just dumping
lat/lon to a JSON than Postgres. Did you guys do some analysis on what the
slow part of this is? Is it really the Postgres query? If so, can't we just
optimise that bit?

On Dec 28, 2016 18:31, "Andres Ferraro" <notifications@github.com> wrote:

In solr the information of lat and long was in other order that is why they
were in the wrong position in the map.
Let's try on test if solr is returning all the items, in my local works
fine with around 4k items.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/MTG/freesound/pull/777#issuecomment-269510692>, or mute
the thread

**Comment by andrebola** [comment]
The problem of the index not been updated could be fixed. But I think the queries can't be optimized since are done with raw sql. 

The idea behind this PR it was to test if the performance was better, but we already now that the problem is that the json file is too big (2mb). The only option to reduce this file is to do the clustering on the server but that's harder.

**Comment by ffont** [comment]
If performance does not change significantly then I would not change the current method.
Maybe we could however add some indication that the page is "loading" so users don't get confused. For example add a rolling loading indicator on top of the map or something like this. Or add a loading bar "loading geotags...".

**Comment by bdejong** [comment]
The problem is the floating point numbers. They explode in JSON as you need
20+ bytes to encode a 4-byte float.

What you could do is encode the data in BSON and use a BSON parser on the
client side. This would optimize stuff dramatically just by changing the
intermediate format. You would gain at least a factor 5 for
encode/download/decode!

For example:
http://stackoverflow.com/questions/7541552/is-a-binary-json-javascript-library-available-for-browsers

Or you could use protocol buffers:
https://github.com/dcodeIO/ProtoBuf.js/

I'm sure there are more binary data transfer types for JavaScript.

On Jan 2, 2017 2:30 PM, "Frederic Font" <notifications@github.com> wrote:

If performance does not change significantly then I would not change the
current method.
Maybe we could however add some indication that the page is "loading" so
users don't get confused. For example add a rolling loading indicator on
top of the map or something like this. Or add a loading bar "loading
geotags...".

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/MTG/freesound/pull/777#issuecomment-269972707>, or mute
the thread

**Comment by ffont** [comment]
That makes total sense...

**Comment by alastair** [comment]
We do this in dunya for some bits of data. We may not even need a schema-based storage format - if you just write out latlnglatlng to a file using 16 or 32-bit integers (e.g. by taking a decimal value and multiplying by 1000), you can read them directly by using Uint16Array in javascript.

**Comment by andrebola** [comment]
I have created a new branch with this changes, see PR #783

**Comment by bdejong** [comment]
@alastair uuuugh, ugly hack! @andrebola I should have read this before commenting on your PR.
please, pretty please user another, nicer intermediary format.

**Comment by ffont** [comment]
I have no preference in any solution (bson, proto buffers or raw binary), but in any case @bdejong you're not stating why shouldn't we use raw binary. To me it looks like I don't see a real difference for such a small problem (surely not in performance?), and using raw binary we could also (probably) reuse some code from Dunya. So I see this as being justified. Unless @bdejong can convince me that using one of the other formats will be worth the change, I won't leave it as it is 🎆

**Comment by bdejong** [comment]
Raw binary has no metadata attached to it. So, there is no way to interpret raw binary data without someone telling you exactly what the format is. I.e. you have to document separately what you are sending.

With any other data serialization format (bson, protobuf, avro, thrift, ...) you get the benefit that the interpretation is human readable.

And the code will look nicer on BOTH ends:

https://github.com/py-bson/bson

```python
>>> import bson
>>> a = bson.dumps({"A":[1,2,3,4,5,"6", u"7", {"C":u"DS"}]})
```

https://github.com/mongodb/js-bson

```javascript
var data = bson.deserialize(data)
```

versus messing around with data/structure packing and unpacking.

**Comment by ffont** [comment]
We have a bit of a mess with this pull request and pull request https://github.com/MTG/freesound/pull/783. I think we decided there is no real advantage on using solr, but we should definitely deploy the bytearray thing. I think this PR should be closed although it contains a conversation relevant to https://github.com/MTG/freesound/pull/783.

**Pull request closed without merging**
