### PR TITLE
Revised Moderation Responses 

### PR DESCRIPTION
**Pull request by Headphaze**
Please let me know if my hyperlinks and line breaks would work the way i've done it. 

Cheers

### CODE REVIEW

**Comment by ffont** [comment]
Thanks for the PR @Headphaze. There are some syntax errors that I'll fix, but I'm not sure I understand the `hyperlink_format ` bit. These text templates I'm afraid can't contain HTML, so the links should be raw. Does that make sense? Also the template buttons add `*` before the text, but maybe now with these more complete templates this is not needed right? I could try to make these templates HTML-enabled also.  What is your preference?

**Comment by Headphaze** [comment]
Damn, it was worth a try. I'm not great with Python so I looked up a way to add hyperlinks into the code. My only issue was that the FAQ links were long. If you could somehow make the templates HTML enabled that would be great.

Oh yes. I forgot to mention the asterisk symbol. Please remove it as it's not necessary. 

Thanks

**Comment by ffont** [comment]
Ok, I'll work on that. But what do you mean the FAQ links were wrong? there were no FAQ links before right?

**Comment by Headphaze** [comment]
There were no FAQ links before. I'm adding them in to direct user's for guidance. What I meant was that the raw URLs **are** long and ugly. :-P

I'll not make any commits to my master branch then, I'll leave it to you.

**Comment by ffont** [comment]
perfect, I'll take it from here. Thanks Sam!

**Comment by ffont** [comment]
closing this PR as the changes were added in d087e9aaacad7cd4bc1c173d0ff007ab4ba578a0

**Pull request closed without merging**
