### PR TITLE
Added javascript check to keep upload size below 1 Gb

### PR DESCRIPTION
**Pull request by P-D-E**
**Issue(s)**
#1419  

**Description**
This PR aims to guard against uploads over 1 Gb, by checking the total size of the files in list, discarding files that won't fit and, in that case, alerting the user.
If the limit ever gets changed in nginx, the code here will have to be updated accordingly.

### CODE REVIEW

**Comment by alastair** [comment]
awesome, thanks for the suggestion about how to handle this issue! I think we can make a few changes to it, but this is a great start. 

We could have an indicator/progress bar next to the file list that shows the total size of all files (perhaps only if it reaches 700mb or so, say "700/1000MB used" and make it get red the closer to 1gb it gets. Then we can show a message here in red "Cannot add the previous file, too big" instead of having an alert. What do you think?

**Comment by P-D-E** [comment]
I've replaced the alert with a call to resetForm to have the red message, painless :)
Now, onto the indicator; keep feedback and further ideas coming!

**Comment by P-D-E** [comment]
I've added a graphic bar below the file list, visible as usage gets above 50%, with green, orange, and red colors, let me know how it goes.

**Comment by ffont** [comment]
Hi, I made some small changes to improve this PR and have it ready for merging. I'd like to push the changes to the same branch in your fork but I don't seem to be able to do it because of lack of permissions. @P-D-E can you give me permissions to push to your fork?

Here are some screenshots of the updates:

less_than_50_no_warning

green_warning

yellow_warning

limit_exceeded

**Comment by P-D-E** [comment]
@ffont : Really nice! You should be able to push your changes now, let me know.

**Comment by ffont** [comment]
Ok, I was able to push now, although I think that I might have a typo in my branch name and this was the reason why I could not push before, so maybe special permission was not really needed at all. Anyway, here's the update. @alastair if you want to have a look, and @P-D-E if it looks good to you; then I'll merge and deploy :)

**Comment by P-D-E** [comment]
@ffont It looks good indeed, happy merging :)

**Pull request merged**
