### PR TITLE
Change exception when paypal does not respond

### PR DESCRIPTION
**Pull request by andrebola**
issue #842

Since this error happened again I checked that the donation was
successfully stored on the DB, so this means the problem is that paypal
sometimes doesn't respond the requests.

### CODE REVIEW

**Comment by alastair** [comment]
The specific 'name or service not known' is due to UPF DNS being bad, and not paypal.
The change to catch `ConnectionError` is fine, however we could also consider using requests sessions to retry 2 or 3 times: https://stackoverflow.com/a/15431343

```python
from requests.adapters import HTTPAdapter
s = requests.Session()
s.mount(settings.paypal_url, HTTPAdapter(max_retries=5))
s.post(settings.paypal_url)
```

**Comment by andrebola** [comment]
@alastair is it really necessary? Since Paypal invoques multiple times the endpoint with the same information.

**Comment by ffont** [comment]
It is Paypal ho sends a request to us right? so I'm not sure I understand well you suggestion @alastair

**Comment by alastair** [comment]
yes, we should be programming defensively. If we can prevent a python exception from being raised by adding a retry loop then we should. We already know that this specific error (cannot resolve hostname) is caused by the UPF infrastructure and that retrying causes it to succeed.

**Comment by andrebola** [comment]
Ok, I made the change and tested in test.freesound.org

**Pull request merged**
