### PR TITLE
Pack download using temporary license file

### PR DESCRIPTION
**Pull request by andrebola**
According to #751, when the user downloads a pack of sounds we create a temporary file with the license information so we can remove the process method in Pack.

### CODE REVIEW

**Comment by bdejong** [comment]
Idea for a small improvement: as we have pack descriptions, should we not
add them to the license file?

**Comment by ffont** [comment]
I was testing this pull request but I don't seem to be able to make it work. 
I deployed in freesound test and it returns 502 responses when trying to download a pack (i.e., http://test.freesound.org/people/xserra/packs/5103/).
How did you test it?

**Comment by andrebola** [comment]
Now is working, it was using the wrong path for the license file (it should use the '/secret/...') and there was a file permission issue.

**Comment by ffont** [comment]
Now I tested and it looks fine.
Once we deploy we should monitor cpu impact of this feature and test with very large packs.

**Pull request merged**
