### PR TITLE
automatic conversion from futurize --stage1 with small fixes

### PR DESCRIPTION
**Pull request by Bomme**
**Issue(s)**
This is a first step for Py3 migration #1083 

**Description**
This is the result of applying _Stage 1: “safe” fixes_ of `futurize`.
Probably the most interesting change in this commit is the use of `absolute_import`.
This caused problems with the mutual imports of `apiv2_utils.py` and `exceptions.py` which I fixed by using an absolute import.

I left out `solr451custom.py` and `solr451pysolr.py` to not cause merge problems with #1614 

**Deployment steps**:
None

### CODE REVIEW

**Comment by ffont** [comment]
Hi @Bomme,
Thanks for this PR!
I'd like to see @alastair's review, but to me it looks fine.
I'd also include the solr files so alastair can at some point merge master to his branch and fix the merging conflicts.

Is this supposed to be ready to merge or you want to do more stuff with it before merging?

**Comment by ffont** [comment]
Thanks for the review @alastair. I think I misread the names of the solr files and I thought these were for solr5x. I'll go ahead and merge this PR then!

**Comment by Bomme** [comment]
This PR is ready to be merged. The next step will be in a separate PR.

> How did you select for which files you used it?

`futurize` auto detects implicit relative imports and adds the `absolute_import`. So if no change is needed, nothing is changed.

**Comment by ffont** [comment]
Hi, I tested the similarity server and tag recommendation server after your changes and I had to make some modifications in the import to make them work (I was having this error `ValueError: Attempted relative import in non-package`). You did not see these errors because these services are not tested (these are actually non django stuff and run in different containers). Not sure if what I did makes sense (see commit changes https://github.com/MTG/freesound/pull/1620/commits/fc80d89da452059716ac617628f62bac9f8e5914), but services work now. If that is fine, then I think the PR is ready to merge.

**Review by ffont — APPROVED** [review]

**Pull request merged**
