### PR TITLE
Expand accordion on sound upload when it has errors

### PR DESCRIPTION
**Pull request by andrebola**
issue #731 

Also #729: Visual changes on sound describe page to sound headers. Note that the following icons are used, we need to credit the author: https://www.flaticon.com/free-icon/keyboard-right-arrow-button_60758

### CODE REVIEW

**Comment by ffont** [comment]
I tested it locally and when there are errors the accordion is expanded but then there are no arrows. I guess this is a bug. 

Regarding the arrows I'm not sure where should we put the attribution. I guess we add a "credits" paragraph in the about section. Nevertheless, aren't there any other arrow signs that we could use? This is just going to be provisional until we release the new UI anyway...

**Comment by alastair** [comment]
We could use a simple http://www.fileformat.info/info/unicode/char/25b6/index.htm or http://www.fileformat.info/info/unicode/char/203a/index.htm for an arrow instead of an additional dependency

**Comment by alastair** [comment]
(fontawesome also has a nice arrow, but I don't think that we should add it if we don't already use it. Something to think about for the next version? - http://fontawesome.io/icon/chevron-right/)

**Comment by andrebola** [comment]
@ffont Make sure to clear the cache of the browser before, since I changed all.css file.

**Pull request merged**
